title: Learn Jekyll
author: tiennm99
email: thisisprivateemail@mail.com
description: > # this means to ignore newlines until "baseurl:"
  This repository is my effort to learn how to use jekyll to create a github page.

# social links
twitter_username: tiennm99 # DO NOT include the @ character, or else the build will fail!
github_username:  tiennm99 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
